Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from sklearn.tree import plot_tree

_, ax = plt.subplots(figsize=(8, 6))
_ = plot_tree(tree, feature_names=feature_name, ax=ax)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mInvalidParameterError[0m                     Traceback (most recent call last)
Cell [0;32mIn[9], line 4[0m
[1;32m      1[0m [38;5;28;01mfrom[39;00m [38;5;21;01msklearn[39;00m[38;5;21;01m.[39;00m[38;5;21;01mtree[39;00m [38;5;28;01mimport[39;00m plot_tree
[1;32m      3[0m _, ax [38;5;241m=[39m plt[38;5;241m.[39msubplots(figsize[38;5;241m=[39m([38;5;241m8[39m, [38;5;241m6[39m))
[0;32m----> 4[0m _ [38;5;241m=[39m [43mplot_tree[49m[43m([49m[43mtree[49m[43m,[49m[43m [49m[43mfeature_names[49m[38;5;241;43m=[39;49m[43mfeature_name[49m[43m,[49m[43m [49m[43max[49m[38;5;241;43m=[39;49m[43max[49m[43m)[49m

File [0;32m/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/sklearn/utils/_param_validation.py:201[0m, in [0;36mvalidate_params.<locals>.decorator.<locals>.wrapper[0;34m(*args, **kwargs)[0m
[1;32m    198[0m to_ignore [38;5;241m+[39m[38;5;241m=[39m [[38;5;124m"[39m[38;5;124mself[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124mcls[39m[38;5;124m"[39m]
[1;32m    199[0m params [38;5;241m=[39m {k: v [38;5;28;01mfor[39;00m k, v [38;5;129;01min[39;00m params[38;5;241m.[39marguments[38;5;241m.[39mitems() [38;5;28;01mif[39;00m k [38;5;129;01mnot[39;00m [38;5;129;01min[39;00m to_ignore}
[0;32m--> 201[0m [43mvalidate_parameter_constraints[49m[43m([49m
[1;32m    202[0m [43m    [49m[43mparameter_constraints[49m[43m,[49m[43m [49m[43mparams[49m[43m,[49m[43m [49m[43mcaller_name[49m[38;5;241;43m=[39;49m[43mfunc[49m[38;5;241;43m.[39;49m[38;5;18;43m__qualname__[39;49m
[1;32m    203[0m [43m[49m[43m)[49m
[1;32m    205[0m [38;5;28;01mtry[39;00m:
[1;32m    206[0m     [38;5;28;01mwith[39;00m config_context(
[1;32m    207[0m         skip_parameter_validation[38;5;241m=[39m(
[1;32m    208[0m             prefer_skip_nested_validation [38;5;129;01mor[39;00m global_skip_validation
[1;32m    209[0m         )
[1;32m    210[0m     ):

File [0;32m/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/sklearn/utils/_param_validation.py:95[0m, in [0;36mvalidate_parameter_constraints[0;34m(parameter_constraints, params, caller_name)[0m
[1;32m     89[0m [38;5;28;01melse[39;00m:
[1;32m     90[0m     constraints_str [38;5;241m=[39m (
[1;32m     91[0m         [38;5;124mf[39m[38;5;124m"[39m[38;5;132;01m{[39;00m[38;5;124m'[39m[38;5;124m, [39m[38;5;124m'[39m[38;5;241m.[39mjoin([[38;5;28mstr[39m(c)[38;5;250m [39m[38;5;28;01mfor[39;00m[38;5;250m [39mc[38;5;250m [39m[38;5;129;01min[39;00m[38;5;250m [39mconstraints[:[38;5;241m-[39m[38;5;241m1[39m]])[38;5;132;01m}[39;00m[38;5;124m or[39m[38;5;124m"[39m
[1;32m     92[0m         [38;5;124mf[39m[38;5;124m"[39m[38;5;124m [39m[38;5;132;01m{[39;00mconstraints[[38;5;241m-[39m[38;5;241m1[39m][38;5;132;01m}[39;00m[38;5;124m"[39m
[1;32m     93[0m     )
[0;32m---> 95[0m [38;5;28;01mraise[39;00m InvalidParameterError(
[1;32m     96[0m     [38;5;124mf[39m[38;5;124m"[39m[38;5;124mThe [39m[38;5;132;01m{[39;00mparam_name[38;5;132;01m!r}[39;00m[38;5;124m parameter of [39m[38;5;132;01m{[39;00mcaller_name[38;5;132;01m}[39;00m[38;5;124m must be[39m[38;5;124m"[39m
[1;32m     97[0m     [38;5;124mf[39m[38;5;124m"[39m[38;5;124m [39m[38;5;132;01m{[39;00mconstraints_str[38;5;132;01m}[39;00m[38;5;124m. Got [39m[38;5;132;01m{[39;00mparam_val[38;5;132;01m!r}[39;00m[38;5;124m instead.[39m[38;5;124m"[39m
[1;32m     98[0m )

[0;31mInvalidParameterError[0m: The 'feature_names' parameter of plot_tree must be an instance of 'list' or None. Got 'Flipper Length (mm)' instead.

